version: '3.7'
services:
  app:
    container_name: metrics-app
    image: metrics-app
    build: ./app
    ports:
      - "3000:3000"
    environment:
      GITHUB_TOKEN: ${GITHUB_TOKEN}
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PORT: 3000
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - "./app/src:/usr/src/app/src"
    networks:
      - network
      - network2

  postgres:
    container_name: postgres
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_MAX_CONNECTIONS=100
      - PGDATA=./data/postgres-data
      - PGUSER=postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - network

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    user: root
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    volumes:
      - ./data/pgadmin-data:/var/lib/pgadmin

networks:
  network:
    driver: bridge
    name: postgres_network
  network2:
    driver: bridge
    name: cronjob_network
