apiVersion: v1
kind: Service
metadata:
  name: postgres-loadbalancer
spec:
  selector:
    app: postgres-app
  ports:
    - protocol: TCP
      port: 80  
      targetPort: 5432  # Port on the pod that the service should forward to
  type: LoadBalancer  # Exposes the service internally within the cluster
