apiVersion: v1
kind: Service
metadata:
  name: metrics-app
spec:
  selector:
    app: metrics-app
  ports:
    - protocol: TCP
      port: 3000  
      targetPort: 3000  # Port on the pod that the service should forward to
  type: ClusterIP  # Exposes the service internally within the cluster
