apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432  # Port on which your PostgreSQL database is running
      targetPort: 5432  # Port on the pod that the service should forward to
  type: ClusterIP  # Exposes the service internally within the cluster