version: 2
jobs:
  build:
    docker:
      - image: circleci/node:14

    steps:
      - checkout

      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "package-lock.json" }}
            - dependency-cache-

      - run:
          name: Install dependencies
          command: npm ci

      - run:
          name: Run tests
          command: npm test

      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - node_modules

      - deploy:
          name: Deploy with Docker Compose
          command: docker-compose up -d --build

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build