version: 2
jobs:
  build:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.18
      - run:
          name: Use secret
          command: echo $DOCKERHUB_ID
          environment:
            DOCKERHUB_ID: ${{ secrets.DOCKERHUB_ID }}
      - run:
          name: Use secret
          command: echo $DOCKERHUB_PWD
          environment:
            DOCKERHUB_PWD: ${{ secrets.DOCKERHUB_PWD }}
      - run:
          name: Build and deploy to Docker Hub
          command: |
            echo "$DOCKERHUB_PWD" | docker login -u "$DOCKERHUB_ID" --password-stdin
            docker-compose up -d --build
            docker-compose push

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: circleci-project-setup