version: 2
jobs:
  build:
    environment:
      IMAGE_NAME: metrics 
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.18
      - run:
          name: Build Docker image
          command: |
            export GITHUB_TOKEN=$GITHUB_TOKEN
            docker-compose up -d --build
      # Push all Docker images
      - run:
          name: Push Docker images
          command: |
            echo "$DOCKERHUB_PWD" | docker login -u "$DOCKERHUB_ID" --password-stdin
            images=$(docker-compose images -q)
            for image_id in $images; do
              repository=$(docker image inspect --format='{{ index .RepoTags 0 }}' $image_id)
              docker push $repository
            done
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: circleci-project-setup