version: 2
jobs:
  build:
    docker:
      - image: circleci/metrics

    steps:
      - checkout

      - deploy:
          name: Deploy with Docker Compose
          command: docker-compose up -d --build

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build