version: 2
jobs:
  build:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.18
      - run:
          name: Check Docker Hub credentials
          command: |
            if [[ -z "${{ secrets.DOCKERHUB_PWD }}" || -z "${{ secrets.DOCKERHUB_ID }}" ]]; then
              echo "ERROR: Docker Hub credentials not provided."
              exit 1
            fi
      - run:
          name: Use secret - ID
          command: echo $DOCKERHUB_ID
          environment:
            DOCKERHUB_ID: ${{ secrets.DOCKERHUB_ID }}
      - run:
          name: Use secret - PWD
          command: echo $DOCKERHUB_PWD
          environment:
            DOCKERHUB_PWD: ${{ secrets.DOCKERHUB_PWD }}
      - run:
          name: Build and deploy to Docker Hub
          command: |
            echo "$DOCKERHUB_PWD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker-compose up -d --build
            docker-compose push

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: circleci-project-setup