version: 2
jobs:
  build:
    environment:
      IMAGE_NAME: metrics 
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.18
      - run:
          name: Build Docker image
          command: |
            export GITHUB_TOKEN=$GITHUB_TOKEN
            docker-compose up -d --build
      # Push all Docker images
      - run:
          name: Push Docker images
          command: |
            echo "$DOCKERHUB_PWD" | docker login -u "$DOCKERHUB_ID" --password-stdin
            # Define the repository names
            metrics_repo="samkryszto/metrics-app"
            pgadmin_repo="samkryszto/pgadmin"
            postgres_repo="samkryszto/postgres"

            # Tag and push the images
            docker-compose images --services | while read -r service; do
              # Get the image ID for the service
              image_id=$(docker-compose images -q $service)

              # Tag the image with the corresponding repository and :latest tag
              case $service in
                metrics-app)
                  docker tag $image_id $metrics_repo:latest
                  docker push $metrics_repo:latest
                  ;;
                pgadmin)
                  docker tag $image_id $pgadmin_repo:latest
                  docker push $pgadmin_repo:latest
                  ;;
                postgres)
                  docker tag $image_id $postgres_repo:latest
                  docker push $postgres_repo:latest
                  ;;
                *)
                  echo "Unknown service: $service"
                  ;;
              esac
            done
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: circleci-project-setup